# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66d2077e9896786d42d228e965e4b6adfdf6139d7ae5610553ea1d0b16ceb0675296da2e1e3cb5d139566ef6af4605511a418a9a1d06504326c5f4df9b6e520

test:
  secret_key_base: e71d0a2c75d640d7cd8fe02c08e1b19235c4ac5f136e5ef0c6bf8df5801b45ee97768d660e95b27d6ab800ef0b2b7193c17b4d99a38fda24824ec8b4ffe5a607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
